---
title: "X_xgBoost_hyperparameter_tuning.Rmd"
author: "tobiasmohl"
date: "2025-09-25"
output: html_document
---

# 1. Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(data.table)
  library(xgboost)
  library(dplyr)
  library(mlr3)
  library(mlr3learners)   
  library(mlr3tuning)
  library(mlr3mbo)
  library(paradox)
  library(data.table)
  library(paradox)
})

set.seed(187)

SCRIPT_DIR   <- getwd()
PROJECT_ROOT <- normalizePath(file.path(SCRIPT_DIR, ".."), mustWork = FALSE)

OUTPUT_DIR <- file.path(PROJECT_ROOT, "output")
XGB_DIR    <- file.path(OUTPUT_DIR, "xgBoost_outputs")
TUNING_DIR <- file.path(XGB_DIR, "tuning")

dir.create(TUNING_DIR,  recursive = TRUE, showWarnings = FALSE)

run_name <- "xgBoost_tuning_6"

data_file      <- file.path(XGB_DIR, "data_aggregated.tsv")
training_file  <- file.path(PROJECT_ROOT, "data", "eqtl_files", "training_data_snppg_aggregated.tsv.gz")
outfile  <- file.path(TUNING_DIR, run_name)
dir.create(outfile,  recursive = TRUE, showWarnings = FALSE)

```

# 2. Preparation
```{r}
full_data <- fread(data_file)
training_data <- fread(training_file)
```

# 3.
```{r}
ct_map <- c(
  Ast = "astrocytes",
  MG  = "Microglia",
  OD  = "Oligodendrocytes",
  OPC = "OPC",
  IN  = "Neurons",     # fuse IN  → Neurons
  Ext = "Neurons",     # fuse Ext → Neurons
  End = "Endothelial"
)

remap_ct <- function(x) ifelse(x %in% names(ct_map), ct_map[x], x)

training_data[, celltype := remap_ct(celltype)]
full_data[,     celltype := remap_ct(celltype)]

training_data[, chr := tstrsplit(peak, "-", keep = 1L)]

# Merge on full identity
index_cols <- c("peak", "gene", "celltype", "chr")
training_data <- unique(training_data, by = index_cols)

#trainRe <- training_data[,.(Fixed_P=min(Fixed_P)), by=index_cols]

setkeyv(full_data, index_cols)
setkeyv(training_data, index_cols)
data <- full_data[training_data, nomatch = 0L]

# Labels: 1 = pos, 2 = strong neg -> make 0/1
data[label == 2L, label := 0L]
data <- data[label %in% c(0L, 1L)]

cat(sprintf("Number of training instances: %s\n", nrow(data)))
cat(sprintf("Number of positives: %s\n", sum(data$label == 1L)))
cat(sprintf("Number of negatives: %s\n\n", sum(data$label == 0L)))

trainTable <- data

if (!is.factor(trainTable$label)) {
  # convert 2 -> 0 
  trainTable[label == 2L, label := 0L]
  trainTable <- trainTable[label %in% c(0L,1L)]
  trainTable[, label := factor(label, levels = c(0,1))]
}

catf <- function(...) cat(sprintf(...), "\n")
catf("Rows after merge: %d", nrow(trainTable))
catf("Positives: %d (%.3f%%)", sum(trainTable$label == "1"),
     100 * mean(trainTable$label == "1"))
catf("Chromosomes: %s", paste(sort(unique(trainTable$chr)), collapse = ", "))

```

```{r}
MeasureAupr = R6::R6Class("MeasureAucPr",
                          inherit = mlr3::MeasureClassif,
                          public = list(
                            initialize = function(){
                              super$initialize(
                                id = "classif.aucPr",
                                packages = c("data.table", "PRROC"),
                                properties = character(),
                                predict_type = "prob",
                                range = c(0, 1),
                                minimize = FALSE)
                            }
                          ),
                          
                          private = list(
                            # define score as private method
                            .score = function(prediction, ...) {
                              # define loss
                              aupcr=function(prediction){
                                truth1 <- ifelse(prediction$truth==levels(prediction$truth)[1], 1, 0)
                                auc <-  PRROC::pr.curve(scores.class0=prediction$prob[, 1],
                                                        weights.class0=truth1)$auc.integral
                                return(auc)
                              }
                              
                              # call loss function
                              aupcr(prediction)
                            }))
```

```{r}
task <- TaskClassif$new(
  id      = "xgboost_tree_param",
  backend = trainTable,          # data.table/data.frame with columns: features + 'label' + 'chr'
  target  = "label",
  positive = "1"
)
# [,setdiff(colnames(trainTable), setdiff(feature_cols, "chr")), with=FALSE]

# Mark grouping column for custom LOGO by chromosome (you’ll still instantiate rsmp('custom'))
annoCol <- "chr"
task$set_col_roles(annoCol, add_to = "group", remove_from = "feature")

pred_cols <- setdiff(names(trainTable), c(index_cols, "label", "chr", "gene_id", "Fixed_P")) # TODO remove Fixed_p and run with old data
task$select(pred_cols)   # keep only feature columns as features

rs <- mlr3::rsmp("loo")
rs$instantiate(task)

learner <- lrn("classif.xgboost",
  booster   = "gbtree",
  objective = "binary:logistic",
  nrounds   = 120,         
  eval_metric = "aucpr",
  predict_type = "prob"
)

paramSet <- paradox::ParamSet$new(list(
  eta               = paradox::p_dbl(lower = 0.01,  upper = 0.3),
  max_depth         = paradox::p_int(lower = 3,     upper = 10),
  gamma             = paradox::p_dbl(lower = 0,     upper = 20),
  min_child_weight  = paradox::p_int(lower = 1,     upper = 20),
  subsample         = paradox::p_dbl(lower = 0.5,   upper = 1.0),
  colsample_bytree  = paradox::p_dbl(lower = 0.5,   upper = 1.0),
  lambda            = paradox::p_dbl(lower = 0,     upper = 1000),  # L2 reg
  alpha             = paradox::p_dbl(lower = 0,     upper = 1000)   # L1 reg
))



measure <- msr("classif.logloss")

evalRounds <- 50
terminator <- mlr3tuning::trm("combo",
                              list(mlr3tuning::trm("stagnation", iters=10, threshold=0.001),
                                   mlr3tuning::trm("evals", n_evals=evalRounds)), any=FALSE)

lgbmInst <- mlr3tuning::ti(task=task,
                           learner=learner,
                           resampling=rs,
                           measure=measure,
                           search_space=paramSet,
                           terminator=terminator)

tuner <- mlr3mbo::TunerMbo$new()
tuner$optimize(lgbmInst)

saveRDS(lgbmInst, file.path(outfile, "tuning_instance.rds"))     # full tuning history + results

hp <- as.data.table(lgbmInst$result)

saveRDS(lgbmInst$result, file = file.path(outfile, "best_result.rds"))

```

```{r}
tuningInstance <- readRDS(file.path(outfile, "tuning_instance.rds"))
arch <- as.data.table(tuningInstance$archive$data)
head(arch)
names(arch)

arch[, iter := seq_len(.N)]
best_row <- arch[which.min(classif.logloss)]

ggplot(arch, aes(x = iter, y = classif.logloss)) +
  geom_point(color = "black", size = 1) +
  geom_smooth(se = TRUE, color = "red", fill = "pink", span = 0.3) +
  geom_point(data = best_row, aes(x = iter, y = classif.logloss),
             color = "blue", size = 3) +   # highlight best in blue
  scale_y_log10() +
  labs(x = "Evaluation", y = "Logloss",
       title = "Tuning Trajectory") +
  theme_minimal()

ggplot(arch, aes(x = iter, color = sqrt(classif.logloss), y=eta)) +
  geom_point() +
  geom_smooth(se = TRUE, color = "red", fill = "pink", span = 0.3) +
  geom_point(data = best_row, aes(x = iter, y = gamma),
             color = "blue", size = 3) +   # highlight best in blue
   geom_point(data = subset(arch, iter==18), aes(x = iter, y = gamma),
             color = "red", size = 3) +
  scale_y_log10() +
  labs(x = "Evaluation", y = "Logloss",
       title = "Tuning Trajectory") +
  theme_minimal()

```


